replicaCount: 2

image:
  repository: 905418412825.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
  pullPolicy: Always
  tag: e80c4fb775a7b577df9ff878702608ad69d516af

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi