name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run tests
        run: |
          cd src/frontend
          npm test
          cd ../backend
          npm test

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/frontend:$IMAGE_TAG ./src/frontend
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG

      - name: Build and push Backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/backend:$IMAGE_TAG ./src/backend
          docker push $ECR_REGISTRY/backend:$IMAGE_TAG

      - name: Update ArgoCD manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b update-image-${{ github.sha }}
          
          rm -rf .cache
          
          sed -i "s/tag: .*/tag: ${{ github.sha }}/" kubernetes/helm-charts/frontend/values.yaml
          sed -i "s/tag: .*/tag: ${{ github.sha }}/" kubernetes/helm-charts/backend/values.yaml
          
          git add kubernetes/helm-charts/*/values.yaml
          git commit -m "Update image tags"
          git push origin update-image-${{ github.sha }}

      - name: Google Chat Notification
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: CI/CD Pipeline
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}